trained_model_dir: "/data/ymxue/p2_rnavqvae/alex/gcpvqvae/pretrained_model_best"  # Directory where the trained model is saved
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae_dihedral.yaml"
config_encoder: "config_gcpnet_encoder_rna.yaml"
config_decoder: "config_rna_af2_decoder.yaml"

#data_path: "path/to/evaluation/h5/data"
data_path: "/data/ymxue/p2_rnavqvae/alex/gcpvqvae/data/evaluation_set/cameo_2048_h5"
output_base_dir: "evaluation_results"

batch_size: 8
shuffle: True
num_workers: 0
max_task_samples: 5000000
vq_indices_csv_filename: "vq_indices.csv"  # Name of the CSV file for VQ indices if return_vq_layer is True
alignment_strategy: "kabsch"  # kabsch, no
mixed_precision: "bf16"  # no, fp16, bf16, fp8

tqdm_progress_bar: True

compile_model:
  enabled: False
  mode: null
  backend: inductor
  compile_encoder: True
